# Generated by Django 5.2 on 2026-05-13 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='ставка',
            new_name='rate',
        ),
    ]
