# Generated by Django 5.2 on 2026-05-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_ставка_teacher_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkloadPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('кафедра', models.CharField(max_length=255)),
                ('total_hours', models.IntegerField()),
                ('academic_year', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('SUBMITTED', 'Отправлено'), ('APPROVED', 'Утверждено'), ('RETURNED', 'Возвращено')], default='DRAFT', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
