# Generated by Django 5.2 on 2026-06-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_workloadplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='workloadplan',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
