# Generated by Django 5.2 on 2026-05-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('HEAD', 'Заведующий кафедрой'), ('TEACHER', 'Преподаватель'), ('STUDENT', 'Студент'), ('STUDY_MASTER', 'Учебный мастер')], default='TEACHER', max_length=30),
        ),
    ]
