# Generated by Django 5.2 on 2026-06-09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_workloadplan_approved_at'),
        ('workload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workloadassignment',
            name='plan',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='assignments',
                to='core.workloadplan',
            ),
        ),
    ]
